# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7aaf195e412b5bde5a2d6381bf6eb2e11f0ec7cb45ad2efd9e37d2e285451ac3bfb6251a9f243d9dc5ca8baf535a179fd1c902d175b63cf77e3348226d0b0c07

test:
  secret_key_base: 683962fb7b0d1f8a39f3ee630e1a224e2da36a4157d52c4f4498369b3d13a8629248883d0971b139fcd2b2679480cf9c6a4ea327d4e2ffebf13f6520e996d055

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
